---
title: "Blue Jays Analysis"
output:
  html_document:
    toc: true
    theme: darkly
    highlight: pygments
    code_download: true
lang: en-US
date: "Last Updated: `r format(Sys.Date(), '%B %d, %Y')` `r format(Sys.time(), '%H:%M:%S')`"
---

```{r, echo = FALSE}
bluejays <- read.csv("../data/BlueJays.csv", header = TRUE)
attach(bluejays)
```

### Relationship of BillLength ~ Mass for Blue Jays
```{r}
model_male <- lm(BillLength ~ Mass, data = subset(bluejays, KnownSex == "M"))
model_female <- lm(BillLength ~ Mass, data = subset(bluejays, KnownSex == "F"))

plot(Mass, BillLength, xlab = "Mass (g)", ylab = "Bill Length (mm)", main = "Bill Length vs. Mass for Blue Jays", pch = ifelse(KnownSex == "M", 16, 17), col = ifelse(KnownSex == "M", "blue", "red"))

abline(model_male, col = "blue", lwd = 2)
abline(model_female, col = "red", lwd = 2)

legend("topright", legend = c("Male", "Female"), pch = c(16, 17), col = c("blue", "red"))
```

### Interaction Test
```{r}
model_interaction <- lm(BillLength ~ Mass * KnownSex, data = bluejays)
summary(model_interaction)
```

### Conclusion
Since the P-value of Mass is less than .05, we do not have convincing evidence that the relationship between BillLength and Mass is different by Sex