remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Data Science Notes
description: Notes I take in my Data Science class in Markdown
show_downloads: false
